apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  volumeName: backend-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi















      