apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iacd-app
  template: 
    metadata:
      labels:
        app: iacd-app
    spec:
      containers:
        - name: frontend-container
          image: paulinomariana/iacd_frontend
          ports:
            - containerPort: 3000