apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iacd-app
  template: 
    metadata:
      labels:
        app: iacd-app
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mongo-persistent-volume
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-volume
          persistentVolumeClaim:
            claimName: mongo-pvc